#pragma once

#define PLAYER_CONTROL_FIXED_UPDATE 0x5C2520
#define PLAYER_CONTROL_PLAYER_ID 0x28
#define PLAYER_CONTROL_NETWORKED_PLAYER_INFO 0x58
#define PLAYER_CONTROL_RIGIDBODY_2D 0xD0

#define NETWORKED_PLAYER_INFO_GET_PLAYER_NAME 0x7D6160
#define NETWORKED_PLAYER_INFO_ROLE 0x38

#define RIGIDBODY_2D_GET_POSITION 0x1F798C0
