#pragma once

#define PLAYER_CONTROL_FIXED_UPDATE 0x5C3610
#define PLAYER_CONTROL_PLAYER_ID 0x28
#define PLAYER_CONTROL_NETWORKED_PLAYER_INFO 0x58
#define PLAYER_CONTROL_RIGIDBODY_2D 0xD0

#define NETWORKED_PLAYER_INFO_GET_PLAYER_NAME 0x7DB1E0
#define NETWORKED_PLAYER_INFO_ROLE 0x38

#define RIGIDBODY_2D_GET_POSITION_INJECTED 0x1F96DC0

#define CAMERA_GET_PROJECTION_MATRIX_INJECTED 0x1F18C70
#define CAMERA_GET_VIEW_MATRIX_INJECTED 0x1F19240
#define CAMERA_STATIC_GET_MAIN 0x1F18980

#define SYSTEM_STRING_DATA 0xc
#define SYSTEM_STRING_LENGTH 0x8
